import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Asim app about  component",
  description: "Generated by Asim about",
};

function layout({ children }: { children: React.ReactNode }) {
  return <div>hi i am layout about {children} </div>;
}

export default layout;
